export const LOG_ADDED="LOG_ADDED";
export const LOG_DELETED="LOG_DELETED";
export const LOG_SAVED="LOG_SAVED";
export const LOG_SELECTED="LOG_SELECTED";


export const USER_ADDED="USER_ADDED";
export const USER_DELETED="USER_DELETED";
export const USER_SAVED="USER_SAVED";
export const USER_SELECTED="GROUP_SELECTED";

export const GROUP_ADDED="GROUP_ADDED";
export const GROUP_DELETED="GROUP_DELETED";
export const GROUP_SAVED="GROUP_SAVED";
export const GROUP_SELECTED="GROUP_SELECTED";

export const CALENDAR_ADDED="CALENDAR_ADDED";
export const CALENDAR_DELETED="CALENDAR_DELETED";
export const CALENDAR_SAVED="CALENDAR_SAVED";
export const CALENDAR_SELECTED="CALENDAR_SELECTED";

export const CALENDAR_EVENT_ADDED="CALENDAR_EVENT_ADDED";
export const CALENDAR_EVENT_DELETED="CALENDAR_EVENT_DELETED";
export const CALENDAR_EVENT_SAVED="CALENDAR_EVENT_SAVED";
export const CALENDAR_EVENT_SELECTED="CALENDAR_EVENT_SELECTED";

